### ISSUE TITLE
Decorator syntax

### ISSUE THREAD

**Issue by paradoxxxzero** [AsaAyers/js-hyperclick#106]
Hi and thanks for the great plugin.

Sadly this plugin does not work anymore in many of my files that uses the legacy decorator syntax due to this config: https://github.com/AsaAyers/js-hyperclick/blob/master/lib/core/parse-code.js#L71

Could there be any way to configure it? (I patched for now but it's inconvenient)

**Comment by AsaAyers** [comment]
I'm looking at how I can load your project's Babel config. If you're on Babel 7, can you provide a copy of your Babel config and a minimal example of something that doesn't parse?

**Comment by paradoxxxzero** [comment]
Sure !

.babel.rc
```json
{
  "presets": ["@babel/preset-react", "@babel/preset-env"],
  "plugins": [
    "@babel/plugin-proposal-object-rest-spread",
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    ["@babel/plugin-proposal-class-properties", { "loose": true }],
    "@babel/plugin-transform-runtime"
  ]
}
```
And any jsx file with this decorator style:
```jsx
import { connect } from 'react-redux'
import { withRouter } from 'react-router-dom'

@withRouter
@connect(
  state => ({
    item: state.item,
  })
)
export default class Component extends React.PureComponent {
  render() {
     return (
       <>
         ...
       </>
     )
  }
}
```

**Comment by paradoxxxzero** [comment]
Seems to work great !
Cheers
