### ISSUE TITLE
Absolute paths

### ISSUE THREAD

**Issue by brettz9** [AsaAyers/js-hyperclick#108]
This fork advertises absolute path support: https://github.com/rohithb/js-hyperclick-project-path

If you don't support it, I'd like to request it, and if you do, I'd suggest mentioning this.

Thanks!

**Comment by AsaAyers** [comment]
This project has always been designed to follow Node's resolution algorithm. But I recently added support for you to hook into the resolution process and support any arbitrary resolution strategy you'd like.

For your use case you just need to configure [moduleRoots](https://github.com/AsaAyers/js-hyperclick#moduleroots) in your project, and your custom resolver will need to include something like this:

https://github.com/AsaAyers/js-hyperclick/blob/08399f482db8d69203503ae84740e7b065b0c0ee/custom-resolver.js#L28-L32
