### ISSUE TITLE
custom-resolver.js doesn't work - Unexpected end of JSON input

### ISSUE THREAD

**Issue by rachydro** [AsaAyers/js-hyperclick#111]
Using atom 1.35.1, hyperclick 0.1.5 and js-hyperclick 1.17.0, macOS High Sierra 10.13.6

I have custom paths set up in webpack so that in import statements, `modules` refer to `app/modules` and `root` refers to `app`. When I press command and hover over the path and click, it gives me an error: unexpected end of JSON input as below.

`webpack.common.js` file:
```
  resolve: {
    alias: {
      root: path.resolve(__dirname, '../app'),
      modules: path.resolve(__dirname, '../app/modules')
    },
    modules: [path.resolve(__dirname, '../app'), path.resolve(__dirname, '../node_modules')]
  },

```

Import syntax example:
```
import Progress from 'modules/common/components/Progress';
import forms from 'root/constants/formConstants';

```

My setup in `package.json`:
```
  "hyperclick": {
    "versions": {
      "0.1.0": "getProvider"
    }
  },
  "moduleRoots": [ "", "custom-resolver.js" ],
```

`custom-resolver.js` file:
```
"use babel"
/* eslint-disable no-unused-vars */

// If you want to use ES6 module syntax, you will need "use babel" at the top of
// your resolver. Atom will transpile it automatically.
import path from "path"

// spec/fixtures/all-imports.js has some imports that run through this custom
// resolver. I don't know what you might use basedir for, but you have it if you
// need it. In the case of `all-imports.js` basedir would be the absolute path
// to `js-hyperclick/spec/fixtures` without the trailing slash.
export default function customResolver({ basedir, moduleName }) {
  // You can use whatever strategy you want to convert your modules
  const [prefix, ...rest] = moduleName.split("/")

  // Whatever you return will be resolved realative to the file that imported
  // it.
  // if (prefix === "this-directory") {
  //   return "./" + rest.join("/")
  // }

  if (prefix === "root") {
    // I think it's probably best to return an absolute path like this most of
    // the time.
    return path.join(__dirname, "app", rest.join("/"))
  }

  if (prefix === "modules") {
    // I think it's probably best to return an absolute path like this most of
    // the time.
    return path.join(__dirname, "app/modules", rest.join("/"))
  }

  // Meteor style imports. These are NOT node compatible because `/` is the root
  // of your filesystem.
  if (moduleName[0] === "/") {
    return path.join(__dirname, moduleName)
  }

  // The module `atom` and node built in modules have custom handling that open
  // a URL. If for some reason you have a module that can't be resolved by
  // normal means, you can also link out to documentation somewhere.
  if (moduleName === "url-example") {
    return "https://atom.io/packages/js-hyperclick"
  }
}


```
Error message
```
Uncaught SyntaxError: Unexpected end of JSON input
file:///Users/hedgeable/Downloads/Atom.app/Contents/Resources/app.asar/static/index.html:93
Hide Stack Trace
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at loadModuleRoots (/Users/hedgeable/.atom/packages/js-hyperclick/lib/core/resolve-module.js:36:23)
    at resolveWithCustomRoots (/Users/hedgeable/.atom/packages/js-hyperclick/lib/core/resolve-module.js:53:17)
    at resolveModule (/Users/hedgeable/.atom/packages/js-hyperclick/lib/core/resolve-module.js:150:30)
    at followSuggestionPath (/Users/hedgeable/.atom/packages/js-hyperclick/lib/js-hyperclick.js:109:22)
    at Object.callback (/Users/hedgeable/.atom/packages/js-hyperclick/lib/js-hyperclick.js:169:11)
    at t.default._confirmSuggestion (/Users/hedgeable/.atom/packages/hyperclick/index.js:1:158042)
    at t.default._onMouseDown (/Users/hedgeable/.atom/packages/hyperclick/index.js:1:159072)

```

Directory structure:
![Screen Shot 2019-04-03 at 5 01 26 PM](https://user-images.githubusercontent.com/33498751/55512872-3b9cdc00-5632-11e9-8a76-9de3ce5c3f37.png)

**Comment by AsaAyers** [comment]
`    at loadModuleRoots (/Users/hedgeable/.atom/packages/js-hyperclick/lib/core/resolve-module.js:36:23)`

That line is where it's parsing the `package.json` nearest to the file you are editing. Can you verify that your `package.json` doesn't have any trailing commas or anything? That's usually my problem when editing json files. `node -p "JSON.parse(fs.readFileSync('./package.json'))"`.

And you don't need the `hyperclick` in your `package.json`, that's for atom plugins' `package.json`. And I'm not sure what the empty string in your `moduleRoots` will do.

**Comment by rachydro** [comment]
You're right, my `package.json` had an unclosed bracket! I'm able to open all the files outside the `modules` directory but import statements in the `modules` directory sometimes won't open (or doesn't have a link when I hover). Do you know how I can fix this issue?  @AsaAyers 

for example no links show when I hover here:
modules > investmentProfile > containers > InvestmentProfileContainer.js
```
import React, { PureComponent } from 'react';
import PropTypes from 'prop-types';
import { connect } from 'react-redux';
import { bindActionCreators } from 'redux';
import { push } from 'connected-react-router';

import InvestmentProfile from '../components/InvestmentProfile';
import * as selectors from '../selectors';
import * as apiSelectors from 'root/api/selectors';
import * as actionCreators from '../actions';
import { assetToColumnConverter, monetaryAnswerConverter } from 'root/utils/converters';
import { validateSingleAnswer, validateStep } from 'root/utils/answerValidators';
import questionTypes from 'root/constants/questionTypeConstants';
import config from 'root/config';
import { Routes } from 'root/constants/routeConstants';
```
for example no links show when I hover here:
modules > investmentProfile > containers > InvestmentProfileContainer.js
```
import React, { PureComponent } from 'react';
import PropTypes from 'prop-types';
import { connect } from 'react-redux';
import { bindActionCreators } from 'redux';
import { push } from 'connected-react-router';

import InvestmentProfile from '../components/InvestmentProfile';
import * as selectors from '../selectors';
import * as apiSelectors from 'root/api/selectors';
import * as actionCreators from '../actions';
import { assetToColumnConverter, monetaryAnswerConverter } from 'root/utils/converters';
import { validateSingleAnswer, validateStep } from 'root/utils/answerValidators';
import questionTypes from 'root/constants/questionTypeConstants';
import config from 'root/config';
import { Routes } from 'root/constants/routeConstants';
```

**Comment by AsaAyers** [comment]
If you open the developer tools in Atom (`View > Developer > Toggle Developer Tools`) you can put this in the console: `localStorage.debug="js-hyperclick*"`. After that js-hyperclick will provide additional logs in that console about what's going on.

If nothing in that file underlines, it usually means there was an error parsing the file. In the past that has been caused by using syntax js-hyperclick doesn't understand yet, but I upgraded to Babel7 and tried to get it to support all available syntax. It even tries to load your babel config in case you have some non-standard plugins.

Here is what a parse error might look like with the additional debugging turned on.
![image](https://user-images.githubusercontent.com/324999/55581898-e82e9a80-56d2-11e9-8215-b6ba291926bb.png)

**Comment by rachydro** [comment]
Oh you're absolutely right! I commented out what was inside the component block and I was able to navigate to files when I hovered on the links. I noticed that whenever I have <React.Fragment></React.Fragment> in the JSX it would throw an error in the console with the parser, is this error coming from the js-hyperclick library or is there something else that I should fix?

```
class LocationParser extends CommentsParser {
  raise(pos, message, {
    missingPluginNames,
    code
  } = {}) {
    const loc = getLineInfo(this.input, pos);
    message += ` (${loc.line}:${loc.column})`;
    const err = new SyntaxError(message);
    err.pos = pos;
    err.loc = loc;

    if (missingPluginNames) {
      err.missingPlugin = missingPluginNames;
    }

    if (code !== undefined) {
      err.code = code;
    }

    throw err;
  }

}
```
<img width="811" alt="Screen Shot 2019-04-04 at 5 59 23 PM" src="https://user-images.githubusercontent.com/33498751/55591507-ab2ecc00-5703-11e9-84f5-26c13c3c7f31.png">

**Comment by AsaAyers** [comment]
Do you have a Babel configuration file that `js-hyperclick` can automatically detect? `.babelrc`, `.babelrc.js`, `babel.config.js`, etc. That error looks like JSX isn't enabled, but the default config enables it.

https://github.com/AsaAyers/js-hyperclick/blob/f21d5d28a80560ca9646d63113b839cdbdacbb73/lib/core/parse-code.js#L76

**Comment by rachydro** [comment]
It all works now! You were right, I installed the @babel/plugin-syntax-jsx module and included it in the .babelrc. Thanks so much for your help! Excited to get this working. :D
