### ISSUE TITLE
Hyperclick fires after click.

### ISSUE THREAD

**Issue by josias-r** [AsaAyers/js-hyperclick#118]
I'm using js-hyperclick 1.18.0 and I love it!
Sometimes I have this strange issue, that hyperclick gets triggered when pressing cmd (I'm on macOS) **after** I have clicked an imported module i.e.

It seems to only happen (every time though) when freshly opening a file.
My steps to reproduce:
Open a file -> click on an imported const -> press cmd after click -> hyperclick gets triggered

I didn't find any errors in the developer console regarding this issue.

<!--
Please go read the FAQ in this project's README.md before opening your issue.
--!>

**Comment by josias-r** [comment]
@AsaAyers

**Comment by AsaAyers** [comment]
js-hyperclick is a provider for [hyperclick](https://atom.io/packages/hyperclick), so it doesn't handle the trigger. If you don't have hyperclick, you may be using [atom-ide-ui](https://atom.io/packages/atom-ide-ui). I don't seem to be able to reproduce the issue. You can run `apm ls` to see what other packages you have installed.

**Comment by josias-r** [comment]
Hyperclick does work and I don't have atom-ide-ui installed. It's just on my macbook where I have the problem as described above. Also, I only have the problem with js-hyperclick and not with the original [hyperlink](https://atom.io/packages/hyperclick).

Here is a list of my installed community packages:

<details><summary>view</summary>
<p>


```
Community Packages (32) /Users/josias_r/.atom/packages
├── atom-import-cost@1.2.0
├── atom-typescript@13.3.0
├── atom-wrap-in-tag@0.6.0
├── autocomplete-js-import@1.4.0
├── autocomplete-paths@2.12.2
├── busy-signal@2.0.1
├── color-picker@2.3.0
├── docblockr@0.13.7
├── emmet@2.4.3
├── file-icons@2.1.35
├── git-plus@8.7.1
├── highlight-selected@0.16.0
├── hyperclick@0.1.5
├── intentions@1.1.5
├── js-hyperclick@1.18.0
├── language-babel@2.85.0
├── language-markdown@0.37.0
├── linter@2.3.1
├── linter-eslint@8.5.5
├── linter-htmlhint@1.6.2
├── linter-php@1.6.1
├── linter-stylelint@4.4.9
├── linter-ui-default@1.8.0
├── markdown-writer@2.11.7
├── minimap@4.29.9
├── minimap-linter@2.2.1
├── pigments@0.40.2
├── platformio-ide-terminal@2.9.4
├── prettier-atom@0.57.2
├── project-manager@3.3.7
├── script@3.18.1
└── sync-settings@0.8.6
```

</p>
</details>

**Comment by josias-r** [comment]
I'm now observing that it always opens the babel.config.js when pressing cmd after opening a file... Maybe this bug only exists in git/node project folders...

**Comment by AsaAyers** [comment]
Because your config file is JavaScript, js-hyperclick has to just execute it and see what it returns. So when it encounters a new config file it opens and is supposed to show a notification asking if you trust this file. You can find the list of trusted files (by hash) in `edit > config` `js-hyperclick.trustedFiles`.

**Comment by josias-r** [comment]
Alright, seems like that has fixed it, but why does a random file inside the project has to run the babel config?

**Comment by josias-r** [comment]
closing, but still curious about an answer :)
