### ISSUE TITLE
Support AMD

### ISSUE THREAD

**Issue by mokkabonna** [AsaAyers/js-hyperclick#12]
Would be nice if AMD imports was working the same way as require. Might need to read a config file to get the paths correct.

**Comment by AsaAyers** [comment]
I'm not interested in supporting AMD. AMD tends to require quite a bit of configuration and have a few different flavors.

I used RequireJS for years with a half dozen projects and I'd never consider AMD again for a project.

**Comment by mokkabonna** [comment]
I din't ask you to marry AMD, just consider supporting it :)

I'll fork then.

**Comment by AsaAyers** [comment]
You're welcome to fork, or even make your own scanner that integrates with [hyperclick](https://atom.io/packages/hyperclick). I just don't see a future in AMD, so I won't invest time in supporting it. It's the same reason I won't publish a CoffeeScript version of this even though I [used to maintain one](https://atom.io/packages/coffee-links) before I switched to hyperclick.

**Comment by mokkabonna** [comment]
I actually agree with you on the long term future of AMD and coffeescript as well. But I and many with me still need to use AMD probably for several years in existing projects.

Will probably create a stand alone amd-hyperclick I guess, instead of publishing a fork of this.

**Comment by AsaAyers** [comment]
Thanks :) I think that's an ideal answer.
