### ISSUE TITLE
Find usages?

### ISSUE THREAD

**Issue by sslash** [AsaAyers/js-hyperclick#14]
Is it out of scope for this package to also support find usages of a file?
Say you right click on a file, press find usage, and get a list of all the files that reference the current file.
For instance.

**Comment by AsaAyers** [comment]
Yes, I think that is outside the scope of this project. If it weren't I think it would add more complexity than you expect. If you want to write your own addon that helps with this here are some things you might want to think about.

* Many scanning addons including js-hyperclick scan the buffer of the open file. To find references you're going to need to read and scan every file in the project.
* Such an addon has to decide how to handle compile-to-javascript languages. Should it scan CoffeeScript? TypeScript? future-ES* (JS with ES7+ extensions)?
* Should it find references to CSS files? With webpack I sometimes `require('./some_styles.css')`, I can also require images.
* Do you want to support other loaders? AMD (#12)? What about [Webpack Loaders](http://webpack.github.io/docs/using-loaders.html)?
