### ISSUE TITLE
jump to function definition

### ISSUE THREAD

**Issue by geddski** [AsaAyers/js-hyperclick#15]
this would be great as well as variables

**Comment by AsaAyers** [comment]
Can you provide an example of code where this doesn't work?

**Comment by geddski** [comment]
you betcha. 

```js
var test = {
  isWorking: false,
  go: function(){
    console.log('go');
  }
}

test.go();
test.isWorking = false;
```

`test` gets underlined and can be jumped to, but `go` function and `isWorking` property do not.

**Comment by AsaAyers** [comment]
This package only tracks variables. I agree it would be nice, but with as dynamic as JavaScript is, I don't see any way to support object properties reliably.

```js
var test = {
  isWorking: false,
  go: function(){
    console.log('go');
  }
}

const key = 'go'
test.go = function() { console.log('new function') }
text[key] = function() { }

var test2 = test
test.go();
test2.go();
test.isWorking = false;
```

Here are just a few of the ways that make that kind of tracking difficult.
