### ISSUE TITLE
Configure additional module directories to search

### ISSUE THREAD

**Issue by AsaAyers** [AsaAyers/js-hyperclick#17]
```
.
└── src
    ├── app
    │   └── main.js
    └── lib
        └── foo.js
```

In a project structured like this some people configure `lib` as a module directory. This lets `main.js` use `require('foo')` instead of `require('../lib/foo')`

**Comment by gothy** [comment]
Sometimes even simpler.
Everything in `src/` is mapped with aliases.

**Comment by dictions** [comment]
Is this already set up to work with aliases?

**Comment by anaibol** [comment]
++1!

**Comment by vjpr** [comment]
This should be a per-project setting. How about a `.jshyperclick.js` file? This would be a JS file that would export a function that would get the module dirs - allowing custom webpack configs, etc.

**Comment by anaibol** [comment]
Maybe just ".jshyperclick"

**Comment by vjpr** [comment]
I prefer with the `.js` so that when you are editing it, it is syntax highlighted correctly.

Most tools allow both.

The most important thing is that its Javascript and not JSON.

**Comment by mctep** [comment]
Hello!

There are disscussion about per-project settings https://github.com/atom/atom/issues/5168 and plugin https://github.com/danielbrodin/atom-project-manager

I think in the future it will be common decision in atom core.

Now I just add `moduleDirectory` config in `js-hyperclick/lib/suggestions.js` file for `js-hyperclick` plugin after each update. But it affects whole projects:

```js
function resolveModule(textEditor, module) {
    const basedir = path.dirname(textEditor.getPath())
    const options = {
        basedir,
        extensions: atom.config.get('js-hyperclick.extensions'),
        // it is my custom options
        moduleDirectory: [
          'node_modules',
          'src',
          'src/lib'
        ]
    }
   // ...
}
```

**Comment by UziTech** [comment]
Could we also include [NODE_PATH](https://nodejs.org/api/modules.html#modules_loading_from_the_global_folders) environmental variable for module directorys?

**Comment by kabbi** [comment]
May I suggest implementing some modular solution, like [eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import#resolvers) does? I think that atom's service discovery may be useful here to provide a mechanism for module resolver packages.
Or even reuse eslint resolver plugins. They already support node-style and webpack-style requires.

**Comment by luqmaan** [comment]
Fixed by #29

**Comment by sompylasar** [comment]
FYI, the aforementioned PR #29 wasn't merged because of the need of per-project configuration.

**Comment by sompylasar** [comment]
It's been almost a year, please add support for a `.js-hyperclick.js` config file. If some day per-project configuration will be implemented differently, the config file may become a fallback for those who doesn't use per-project configuration.
