### ISSUE TITLE
Add a shortcut to go back to the previous location(s)

### ISSUE THREAD

**Issue by jakubholynet** [AsaAyers/js-hyperclick#19]
Once I click on a variable to navigate to it (perhaps clicking on another one to go further ...), is there a way to go back to the previous position(s)? Thx!

**Comment by AsaAyers** [comment]
No, there isn't anything keeping track of the last location. I'm going to edit the title to turn this into a feature request for that.

**Comment by jakubholynet** [comment]
Hi, thanks for the quick response!

I have in the meantime found 2 plugins, cursor-history and last-cursor-position that are likely to do that.

So perhaps it would be enough to recommend to install one of those in the description?

**Comment by AsaAyers** [comment]
I'm going to leave this up to other packages to solve.
