### ISSUE TITLE
require to package.json is not clickable

### ISSUE THREAD

**Issue by capaj** [AsaAyers/js-hyperclick#2]
I have a require like:
```
var pjson = require('./package.json')
```
and I would expect to be able to click to `package.json` and get to that file

**Comment by AsaAyers** [comment]
clicking `pjson` should take you there, but you're right, I should also make the import paths clickable.

**Comment by capaj** [comment]
@AsaAyers yeah, that works, good to know

**Comment by AsaAyers** [comment]
Fixed in v1.2.0. I have some code where the require isn't assigned to a variable. Before v1.2.0 there's no way to follow those.
