### ISSUE TITLE
 startup time is too longer than other packages

### ISSUE THREAD

**Issue by SimplyY** [AsaAyers/js-hyperclick#21]
startup time is too longer than other packages. This package added 317ms to startup time. Has any way to optimize the performance?

![image](https://cloud.githubusercontent.com/assets/8455579/14060017/d91276d2-f390-11e5-8479-4094f096abb0.png)

**Comment by AsaAyers** [comment]
I don't know how to make it any faster. It doesn't look like it's doing any unnecessary work I could remove.

Pull Requests are always welcome if anyone knows how to improve this :)
