### ISSUE TITLE
a variable doesn't become clickable if you are hovered on it before pressing CTRL

### ISSUE THREAD

**Issue by capaj** [AsaAyers/js-hyperclick#3]
this caused me to question whether this package works properly, because I have a habit of pointing my mouse first, then pressing CTRL and clicking. With this package I currently have to first press CTRL and then point my mouse. Couldn't it work even when hovered on it before pressing CTRL?

**Comment by AsaAyers** [comment]
The actual highlighting behavior is handled by [hyperclick](https://atom.io/packages/js-hyperclick). Maybe you can open an issue there.
