### ISSUE TITLE
Does it work for OSX?

### ISSUE THREAD

**Issue by howardhsien** [AsaAyers/js-hyperclick#31]
I installed js-hyperclick in my atom in OSX. However, no matter which key I click with(alt,cmd, ctrl, shift), it does not work.

**Comment by AsaAyers** [comment]
You need to have `hyperclick` installed and this package conflicts with `atom-typescript`, so you have to remove that one if you have it.

**Comment by AsaAyers** [comment]
Good news! If you uninstalled `atom-typescript`, you can reinstall it now. v10.1.7 does not clonflict with js-hyperclick

**Comment by AsaAyers** [comment]
I'm closing and assuming either `hyperclick` was missing, or you had an incompatible `atom-typescript`.
