### ISSUE TITLE
jump to import

### ISSUE THREAD

**Issue by opensourceportfolio** [AsaAyers/js-hyperclick#34]
Hi, 

js-hyperclick is great. The one thing I'd like it to do differently though is when cmd-clicking on something that was imported, I would like it to go to the import statement first instead of trying to navigate to the module where it is defined. 

Thank you

**Comment by AsaAyers** [comment]
I'm not sure when I'll have time to add it, but it sounds like a good candidate for a new option to me. 

If you (or anyone) is interested in contributing that I suggest:
1. A new `Jump to import` option
2. When it's on it jumps to the import
3. When you arrive at the import you can still ctrl+click on the path to jump out to the other file exactly as it behaves now.

**Comment by AsaAyers** [comment]
If you activate this option, here is how it works:

![selection_017](https://cloud.githubusercontent.com/assets/324999/19014840/8349ff12-87ac-11e6-94cf-52812d4b5477.png)
