### ISSUE TITLE
Duplicate "moduleRoots" options in plugin settings

### ISSUE THREAD

**Issue by AStaroverov** [AsaAyers/js-hyperclick#36]
I dont want write something unique params in package.json, becouse it needless for other ppls from my project.

**Comment by AsaAyers** [comment]
Because `moduleRoots` is specific to your project I decided the configuration will go in `package.json`. You don't have to use it.

**Comment by AsaAyers** [comment]
If you want to look through the history of this feature check out 

https://github.com/AsaAyers/js-hyperclick/pull/27
https://github.com/AsaAyers/js-hyperclick/issues/25
https://github.com/AsaAyers/js-hyperclick/issues/17
