### ISSUE TITLE
'error parsing' errors when using Flowtype 'exact object' syntax

### ISSUE THREAD

**Issue by jonboiser** [AsaAyers/js-hyperclick#41]
Details:
https://flowtype.org/docs/objects.html#exact-object-types

```javascript
// this breaks js-hyperclick
type = {|
  foo: string
|}
```

This is a new feature in Flow, and I just started experimenting with it today. Any files that use this syntax cause hyperclick to throw an parsing error when doing a click-to-jump.

**Comment by AsaAyers** [comment]
js-hyperclick is not going to support experimental syntax. You will have to wait until the experiment settles and the version of Babel js-hyperclick uses is able to parse it.

Right now it's still on Babel@5, but I have a branch with Babel@6 (Technically Babylon@6)

**Comment by jonboiser** [comment]
i just tested this out on the `upgrade-babel` branch. Babel 6 seems to fix this issue.
