### ISSUE TITLE
js-hyperclick: error parsing 

### ISSUE THREAD

**Issue by sompylasar** [AsaAyers/js-hyperclick#42]
This popping up every time I press Cmd while the pointer is over a variable is really annoying! While writing the code, it's often in an unparseable state.

Could you please at least disable the error popup? It's responsibility of a linter to report parse errors of the file, and it does that job very well.

The improvement to js-hyperclick (or even to the base hyperclick) could be to store code locations of specific items that have once been parsed correctly, and to extrapolate the stored knowledge to the moments when the code is in temporarily unparseable state.

**Comment by AsaAyers** [comment]
Can you verify that you have version 1.9.0? Error on parse was only in an
intermediate release that I think I replaced in less than 24 hours.

**Comment by sompylasar** [comment]
@AsaAyers Yes, `js-hyperclick@1.9.0`, updated just recently, Atom `1.10.2`. Restarted Atom and now it's fine... So probably the update procedure didn't update all of it.

**Comment by lcc19941214** [comment]
Nope...I have the same issue...
Actually I have `js-hyperclick 1.9.0` and `atom 1.12.2`, and nothing goes better after I restared atom and reinstalld js-hyperclick
