### ISSUE TITLE
Use with polymer

### ISSUE THREAD

**Issue by tdesc** [AsaAyers/js-hyperclick#43]
Hello, is it possible to navigate to imports like this? 
I add .html extention in hyperclick plugin
`<link rel="import" href="../../bower_components/polymer/polymer.html">`
`<link rel="import" href="../../bower_components/paper-button/paper-button.html">`

**Comment by AsaAyers** [comment]
I'm not interested in adding support for polymer. `js-hyperclick` is built on Babel, so if Babel can't parse it `js-hyperclick` won't work.

I think this is very similar to my stance on [AMD support](https://github.com/AsaAyers/js-hyperclick/issues/12#issuecomment-161281843) even thought I'm aware Polymer is working against an emerging standard that may have a future.
