### ISSUE TITLE
Unable to resolve project root relative imports

### ISSUE THREAD

**Issue by rohithb** [AsaAyers/js-hyperclick#47]
I'm using js-hyperclick on my meteor project.
The hyperclick works fine on imports with relative path is used. (like `import {something}  from './something.js';`)   
But it does not work if the import statement is as follows:  
`import '/imports/ui/components/partials/sidebar.js'`

The `imports` folder is inside the project's root directory, not on systems root (`/`) directory.
Is there any option on js-hyperclick to work with these kind of imports?

**Comment by AsaAyers** [comment]
See #46 This is not something I'm going to support because the leading slash doesn't mean the root of your project. It means the root of your drive.

**Comment by AsaAyers** [comment]
I just published v1.15 with a new feature I'm calling "Custom Resolvers". It will allow you to add a JS file to your project that can implement your aliases. [PR and documentation](https://github.com/AsaAyers/js-hyperclick/pull/105)

See these for your use case

https://github.com/AsaAyers/js-hyperclick/blob/master/spec/fixtures/moduleRoots.js#L8-L9
https://github.com/AsaAyers/js-hyperclick/blob/master/custom-resolver.js#L30-L32
