### ISSUE TITLE
Function parameters are not recognized

### ISSUE THREAD

**Issue by BlaM** [AsaAyers/js-hyperclick#5]
Function parameters are variables, too :)

Works in Example 2, does not work in Example 1.

    function example1(foo) {
        console.log(foo);
    }

    var example2 = function(foo) {
        console.log(foo);
    }

**Comment by AsaAyers** [comment]
Thanks for the complete example. This is fixed in 1.1.5.

**Comment by BlaM** [comment]
Thank you for fixing so quickly :)
