### ISSUE TITLE
Does this work with OSX?

### ISSUE THREAD

**Issue by surfjedi** [AsaAyers/js-hyperclick#51]
I am trying this in atom 1.12.9, in OSX

It doesn't seem to work? Ctrl+click, alt(option)+click, alt+mouse-over etc do nothing?

I have typescript plugin disabled also.

What am I missing?

**Comment by AsaAyers** [comment]
compatibility with the typescript plugin [was fixed](https://github.com/TypeStrong/atom-typescript/pull/1063), so you can turn it back on.

`js-hyperclick` is a plugin for the package `hyperclick`. It manages the keyboard shortcuts. It looks like the default is `command + click`.

![selection_031](https://cloud.githubusercontent.com/assets/324999/21816219/34940324-d714-11e6-9858-0a53b06f33b6.png)

I'm closing the issue assuming that fixes it, but please let me know if you still need help.
