### ISSUE TITLE
cmd + hover doesn't work, just showing loader/spinner/beachball

### ISSUE THREAD

**Issue by markogresak** [AsaAyers/js-hyperclick#53]
When I try to navigate to reference using cmd+click (which used to work in the past), nothing happens. When I hover over desired signature, only loading cursor is always shown and it doesn't go away. Nothing is reported in the developer console.

I'm not sure what might have broken it, I haven't used it for quite some time. 
I'm sorry for the very vague "it doesn't work" report, but I'm not sure what else to try or what data to provide.

Not sure if this will be useful, but here is output of running [`apm ls`](https://gist.github.com/markogresak/682a6deaacb5a348336f3934630c3c78).

Any ideas on what I could try?

**Comment by AsaAyers** [comment]
I don't see the package `hyperclick` in the list. I need to get moving on #52 and just have it automatically install.

**Comment by markogresak** [comment]
It is a dependency of nuclide.
Although I have checked nuclide option to install dependencies on start, I ran the command manually. 
Nothing changed.

**Comment by AsaAyers** [comment]
If you create a new file, can you jump from `foo` in the `console.log` to where it's defined?
```
const foo = 'foo'


console.log(foo)
```

Normally I don't recommend editing installed packages, but I think it's worth adding some debugging info here. open `~/.atom/packages/js-hyperclick/lib/js-hyperclick.js` and log the `text` between [lines 135 and 136](https://github.com/AsaAyers/js-hyperclick/blob/adbc0e21adf77f68adb0d93af430a66af09c5a0a/lib/js-hyperclick.js#L135-L136). That should tell us whether it's even being called.

**Comment by markogresak** [comment]
I added the console.log where suggested and saved the file. First, I've tried to reload, then close atom, then open in dev mode, never managed to get any input inside the developer tools console. 
Did I do something wrong here, or is there a problem somewhere inside one of the packages?

**Comment by AsaAyers** [comment]
You could also try adding a log between [lines 189 and 190](https://github.com/AsaAyers/js-hyperclick/blob/adbc0e21adf77f68adb0d93af430a66af09c5a0a/lib/js-hyperclick.js#L189-L190). If that isn't called then I think it means that nuclide doesn't actually provide hyperclick functionality. I was looking through hyperclick's commits to see if they broke compatibility and I need to update and found [Make Hyperclick more independent from Nuclide](https://github.com/facebooknuclide/hyperclick/commit/680dccfe40c0be6d313edd4952a099cccc921427)

**Comment by markogresak** [comment]
I've also recorded video, here: https://youtu.be/ssWu88a-OdY
That was prior to what you've suggested in the last comment, but it's still the same anyways.

**Comment by markogresak** [comment]
Also tried to uninstall hyperclick in the view from screenshot above and then re-install it and re-lunch atom. Still nothing.
I'm starting to think I got myself into one of those "how could I be so dumb to miss something so obvious" situations. It's really strange that nothing is happening, no logs, no errors, only crickets.

**Comment by markogresak** [comment]
Update: it's not hyperclick problem. I have disabled every installed package and just installed hyperclick and it works now. Now onto the dull task of re-enabling them one by one to find the black sheep.

If someone in the future stumbles upon this, here's a quick way to disable all packages at once using cli:

```sh
apm ls --bare --installed | cut -d'@' -f1 | xargs apm disable
apm enable hyperclick js-hyperclick 
```

Then check if it works. If it does, you have to isolate which package is causing the issue and either disable/remove it or try to figure it out how to make it play nice with hyperclick.

**Comment by AsaAyers** [comment]
It might help to know that `hyperclick` only takes the suggestion from the first package to reply with one, even if that package's suggestion is that it didn't find anything. This used to be a problem with `atom-typescript`, but [it's been fixed](https://github.com/TypeStrong/atom-typescript/pull/1063).

**Comment by AsaAyers** [comment]
This should show you every package that is a hyperclick provider:

`grep hyperclick.provider\" ~/.atom/packages/*/package.json`

**Comment by markogresak** [comment]
That was really helpful, helped narrow down the hunt to few packages. It turned out that [elmjutsu](https://atom.io/packages/elmjutsu) was doing something funky. Not sure why does it associate with .js files though.
