### ISSUE TITLE
moduleRoots no longer working with hyperclick@0.0.40

### ISSUE THREAD

**Issue by manuelbieh** [AsaAyers/js-hyperclick#55]
I'm not entirely sure if this is caused by something else but I updated my `hyperclick` package 2 days ago (to 0.0.40) and now my moduleRoots config does not work any longer. I'm pretty (though not entirely) sure that it worked on friday before I left the office and before I upgraded hyperclick.

Anyone else having issues with that after upgrading hyperclick?

**Comment by manuelbieh** [comment]
Ok, looks like the support for moduleRoots was dropped in js-hyperclick 1.10.0 and it has nothing to do with the hyperclick update but with an update of js-hyperclick from 1.9.0 to 1.10.1?!
https://github.com/AsaAyers/js-hyperclick/compare/v1.9.0...v1.10.0#diff-06b59d3396227331de66dfe74feb4b0e

**Comment by AsaAyers** [comment]
Most of this package was moved to https://github.com/AsaAyers/js-hyperclick-core. I did not intend to drop support for `moduleRoots`. I'll put it back and release a new version.

**Comment by AsaAyers** [comment]
[moduleRoots test](https://github.com/AsaAyers/js-hyperclick-core/blob/91d6876c2e19ddf224f1646cde3f46fe238a8c62/src/tests/resolve-module.test.js#L102-L112)
[moduleRoots implementation](https://github.com/AsaAyers/js-hyperclick-core/blob/91d6876c2e19ddf224f1646cde3f46fe238a8c62/src/resolve-module.js#L24-L49)

My previous comment is wrong. Support was not removed, I'll update everything I have and see if I can reproduce the problem.

**Comment by manuelbieh** [comment]
Is there a way I can get a debug output so I can provide you with some more information? All I currently get is a flash warning `module components/Loading was not found` - can I see which which paths js-hyperclick is using for the module lookup?

**Comment by AsaAyers** [comment]
I can't verify the `moduleRoots` because I don't use it (and I don't recommend anyone use it). I am able to navigate between modules and to variable declarations. Since the unit test says `moduleRoots` works, I'm going to say I can't reproduce the problem or it's not as simple as just `moduleRoots` being broken.

Are you able to use js-hyperclick to navigate to relative modules and to variable declarations?

**Comment by manuelbieh** [comment]
Yep. Relative modules work fine. My problem is, i'm using a pretty complicated (but in my opinion necessary) setup with npm links in a multi-tenant architecture with shared global modules (for debugging) with a custom webpack resolve path hierachy etc blahblah [insert more bullshit here].

And as originally mentioned, I'm pretty sure it still worked on friday until I did some updates (where I think hyperclick as well as js-hyperclick have been updated). If you can tell me a way how to get some more debug/console information I can see if I can try to create a fix myself 😉

**Comment by AsaAyers** [comment]
You can edit `~/.atom/packages/js-hyperclick/node_modules/js-hyperclick-core/lib/resolve-module.js` and `console.log(config.moduleRoots)` on line 30.

`js-hyperclick` mostly just passes options to [`resolve`](https://www.npmjs.com/package/resolve) and it handles locating files.

**Comment by manuelbieh** [comment]
Ok, I found it. I have no idea why it worked before but following situation:

My filetree:
```
./src/AppBundle/Resources/javascript/
./src/AppBundle/Resources/javascript/components/
./src/AppBundle/Resources/javascript/components/example.js
./src/shared/my-package/
./src/shared/my-package/components/
./src/shared/my-package/components/example.js
./src/shared/my-package/package.json
./package.json
```

**./package.json**
```
"moduleRoots": [
    "./src/AppBundle/Resources/javascript",
    "./src/shared/my-package"
]
```

**./src/AppBundle/Resources/javascript/main.js**
```
import example from 'components/example';
```
(the path is resolved using a custom webpack resolve config → look in `./src/AppBundle/Resources/javascript/` first, if not found, look in `./src/shared/my-package/` as "fallback")

Since `my-package` has its own `package.json`, the `basedir` when looking up modules now seems to be `./src/shared/my-package/` and no longer (has it ever been?!) `./` – where the project's "main" `package.json` is located.

I now added:
```
  "moduleRoots": [
    "../../AppBundle/Resources/javascript",
    "./"
  ],
```

to `./src/shared/my-package/package.json` and it's resolved correctly again.

**Comment by AsaAyers** [comment]
It always uses the `package.json` closest to the file open in the editor. if `./src/shared/my-package/package.json` didn't have a `moduleRoots`, then I don't see how anything in `my-package` could have ever resolved to your `AppBundle`. It looks like the reverse should have worked just fine though.

**Comment by manuelbieh** [comment]
Yes. I'm a bit confused at the moment, but I'm pretty sure it worked fine until recently?! Whatever ... I added the relative paths to the `my-package` package.json and everything is resolved properly again. Sorry for the false alert and thanks for the quick reply! :wink:
