### ISSUE TITLE
Possible to change key mapping in Atom?

### ISSUE THREAD

**Issue by mikeebee** [AsaAyers/js-hyperclick#56]
Hi there, the keyboard shortcut to show the Hyperclick underline and jump to definition on OSX (Command) makes it impossible to create multiple cursors near definitions.

Is there a way to change the key mapping to something else?

I tried copying and changing this keymapping but nothing changed.

```
'.platform-darwin atom-text-editor':
    'alt-cmd-enter': 'hyperclick:confirm-cursor'
```

Many thanks!

**Comment by AsaAyers** [comment]
`js-hyperclick` has no control over key mappings. It is only a plugin for [hyperclick](https://atom.io/packages/hyperclick). But you're probably just looking for hyperclick's settings:

![selection_031](https://cloud.githubusercontent.com/assets/324999/22670666/da234558-ec8f-11e6-813a-747e9a406852.png)

**Comment by mikeebee** [comment]
Oh boy, this is why you don't ask questions before you have coffee. I didn't even see that Hyperclick had settings!

Thank you so much for pointing this out, and thanks for your plugin. It's so very useful!
