### ISSUE TITLE
Request feature: import with absolute path  

### ISSUE THREAD

**Issue by comerc** [AsaAyers/js-hyperclick#60]
I want to use you plugin for absolute path:

```javascript
import MyComponent from 'src/components/MyComponent'
```
[atom-jump-to-import](https://github.com/alexheyd/atom-jump-to-import) work fine, but only with keyboard shortcut. 

Thanks you!

**Comment by AsaAyers** [comment]
FAQ: [I configured {babel,eslint,flow,webpack,etc} to avoid '../' in my imports. How can I configure js-hyperclick?](https://github.com/AsaAyers/js-hyperclick#i-configured-babeleslintflowwebpacketc-to-avoid--in-my-imports-how-can-i-configure-js-hyperclick)

**Comment by BenFlanagan** [comment]
Looks like the readme has been updated, and [the section on moduleRoots](https://github.com/AsaAyers/js-hyperclick#moduleroots) the new equivalent of the above. Just posting this because I found this issue before I found the information in the readme 😅
