### ISSUE TITLE
Click on required module method not working

### ISSUE THREAD

**Issue by prog666** [AsaAyers/js-hyperclick#61]
for example:

```
var myModule = require('./myModule');

myModule.doSomething();
```

clicking on `doSomething` will not open this method declaration, you have to click on myModule first and then search the file for the `doSomething` method

**Comment by AsaAyers** [comment]
That is correct, if you want to be able to click on `doSomething()` it has to be a named import:

```js
import { doSomething } from './myModule'
```

**Comment by prog666** [comment]
but i have to work with a lot of legacy code running on node 0.10, there's on named imports

**Comment by prog666** [comment]
is it so hard to implement? in redux you also do stuff like
```

**Comment by prog666** [comment]
oh, i see now, hyperclyck package doesn't pass parent object to `getSuggestionForWord` method

**Comment by AsaAyers** [comment]
From the FAQ in the readme:

> ## Can you add support for `this.doSomething()`?
> 
> No, There is no way to know for sure what `this` is or what properties it might have. Instead of trying to pick some set of patterns to support and get partly right, I'm just not going to support that at all.
> 
> If you want this you might look into http://ternjs.net/, or if you'll switch to writing Flow instead of standard JavaScript [Nuclide has jump to definition support](http://nuclide.io/docs/languages/flow/#jump-to-definition)

The same applies to modules. This means that I only support the bare minimum of `require`. `js-hyperclick` will track a `module.exports =`, but it does not track anything else related to CommonJS's exports. If you hyperclick into a module that was ES6, but was converted with babel, I don't locate `exports.default = ` either.
