### ISSUE TITLE
Instructions for newbs like myself

### ISSUE THREAD

**Issue by corysimmons** [AsaAyers/js-hyperclick#63]
Sorry...

I installed hyperclick and js-hyperclick. I've been cmd+clicking everything and it doesn't jump to the relevant file (what I'd expect)... it just doesn't do anything.

Hovering over imported stuff reveals a popup telling me where the file is located, but cmd+clicking (any modifier keys for that matter) doesn't jump to the file.

Do I have to do some configuration for every project? I've used php-hyperclick before and don't remember needing to config anything. It also doesn't make sense because it's able to detect where the relevant files are (in the popups) so I can't imagine per-project config would be the problem.

Sorry again for my newbery. Seems to be working for everyone else.

Edit: Just disabled hyperclick stuff, restarted atom, and the popups are still there. So I don't think they have anything to do with hyperclick. :X

**Comment by AsaAyers** [comment]
The trouble with providing instructions is that this package does nothing on its own. Nothing needs to be configured as long as you're following standard conventions used by Node. The optional configuration is documented in the readme.

It looks like php-hyperlick isn't checking if the file is PHP in [getSuggestionForWord](https://github.com/harikt/php-hyperclick/blob/master/lib/main.js#L9). You can have as many Hyperclick providers (js-hyperclick, php-hyperclick, atom-typescript, etc.) but it only accepts the first suggestion. First, disable php-hyperclick and see if that fixes the problem. If it does, then I recommend opening an issue in that project linking to here. atom-typescript [had the same problem](https://github.com/TypeStrong/atom-typescript/pull/1063) and they can probably use a very similar fix.

Thanks for opening this issue, no need to apologize.

**Comment by corysimmons** [comment]
Hmm. I uninstalled php-hyperclick and have the other 3 installed and activated.

I created a new Angular project and it still doesn't seem responsive to cmd-clicks and such. Not sure what I'm doing wrong.

**Comment by AsaAyers** [comment]
Thanks for the update. I've had to go through this process before :disappointed:. Here is what I would do next:

Make sure the shortcuts are what you expect in hyperclick. I'm running Linux and I see this:
![selection_004](https://cloud.githubusercontent.com/assets/324999/24464326/51bec286-145e-11e7-9c21-2ba69c23e92b.png)

When it's working correctly ctrl+hover (or cmd+hover) should underline variables.
![selection_008](https://cloud.githubusercontent.com/assets/324999/24464443/bcc0a5d6-145e-11e7-9412-a34e992772e8.png)

If it's still not working disable all community packages except `hyperclick` and `js-hyperclick`. If it works with just those two, turn on groups of packages until it breaks again.

**Comment by corysimmons** [comment]
It _does_ underline stuff, but when I click, it doesn't go through to the file where the function is defined.

**Comment by AsaAyers** [comment]
Does it go to a local variable declaration? Is there something unusual about your project structure? If you download the `js-hyperclick` repo, do the links work there?

**Comment by corysimmons** [comment]
It seems to work as expected with vanilla JS, but not with a fresh Angular 4 project.

I get the underline on variables, imports, etc. but it doesn't jump to the file where it's defined:

![image](https://cloud.githubusercontent.com/assets/224636/24465736/1e5400f0-147c-11e7-9da4-5d3a159e2181.png)

**Comment by AsaAyers** [comment]
I have no idea what an Angular 4 project looks like. If it does something that isn't standard, then this project isn't likely to change to support it. For example, Meteor uses leading slashes to indicate the root of the project, but in Node a leading slash means the root of your drive. See https://github.com/AsaAyers/js-hyperclick/issues/46

**Comment by AsaAyers** [comment]
Did you maybe turn on "Jump To Import"? If that's on then it will link you to the top of the current file and you can ctrl+click on the path to go to the destination file.

![selection_009](https://cloud.githubusercontent.com/assets/324999/24465863/8d49c5a8-1463-11e7-8254-a63569dcde60.png)

**Comment by corysimmons** [comment]
I've tried it with every combination of settings, and I've added `.ts` files to the list of extensions, and have atom-typescript installed as well.

It doesn't even jump around the same file.

**Comment by corysimmons** [comment]
You can replicate this by installing angular-cli: https://cli.angular.io/
Run `ng new foo; cd foo; atom .`
Install hyperclick, atom-typescript, js-hyperclick. Restart. cmd + click anything.

You get the underlines, but it doesn't jump around at all.

Again, it works as expected with vanilla JS. I haven't tested JSX.

**Comment by AsaAyers** [comment]
> Have you tested js-hyperclick with Typescript yet?

No, js-hyperclick does not and will not support TypeScript. js-hyperclick is for JavaScript.

The underlines mean that one of the hyperclick providers indicates there is something under the cursor. It sounds like `atom-typescript` is actually the one generating the underlines, but they have implemented some other behavior. You'll have to contact them if it isn't working as expected.

**Comment by corysimmons** [comment]
Ugh, sorry for wasting so much of your time. You're a good person.

**Comment by hex13** [comment]
I had the same problem. Atom-typescript was running in my JS(!) file. I uninstalled atom-typescript and it helped.

BTW It's sad state of developing packages in Atom, that there are many packages which do the same and conflict one with other...
