### ISSUE TITLE
Not working with functions defined in objects

### ISSUE THREAD

**Issue by sgsvenkatesh** [AsaAyers/js-hyperclick#65]
<img width="252" alt="screen shot 2017-04-19 at 3 45 41 pm" src="https://cloud.githubusercontent.com/assets/4642729/25175130/4b3fc684-2517-11e7-8a4e-30c24f1011b1.png">

Consider the following example, the plugin works fine when click on `foo` in line 8 but doesn't work with `myname` function in foo - `foo.myname()`

Expected behaviour is when clicked on `myname` in line line 9, should move the cursor to `myname` function definition line 3.

FYI, I read in the docs, @AsaAyers mentioned that `this.doSomething()` will not be supported because 

> "There is no way to know for sure what this is or what properties it might have."

but in the above mentioned case all the properties of the object `foo` are precisely defined and it should be possible to navigate to the definition.

**Comment by AsaAyers** [comment]
The only thing this project tracks is variable declarations in scopes. To do what you want, you need something that can track types. In your extremely narrow toy example, it might seem easy to do on the surface, but I am not going down this path:

![selection_015](https://cloud.githubusercontent.com/assets/324999/25186585/6db788d8-24d5-11e7-80eb-0f64f5ef4fe0.png)

**Comment by sgsvenkatesh** [comment]
IMHO, it is better to have it working partly than not having it at all. I agree that it is nearly not possible to support all the cases but it would be good to have something. Maybe, someday it will be a full grown and supports all the cases. Well, that is the beauty of open-source, isn't it?
