### ISSUE TITLE
Follow requires

### ISSUE THREAD

**Issue by nicolasazrak** [AsaAyers/js-hyperclick#7]
It would be really nice if variables that are imported when clicked goes to the origin file. For example:

Foo.js:

```javascript
export default function Foo(){
/* ... */
}
```

Bar.js

```javascript
import Foo from './Foo';

var bar = new Foo();
```
if I click on Foo from `new Foo();` it would take me to Foo definition in Foo.js, and not Foo import from Bar.js.

**Comment by AsaAyers** [comment]
It does exactly that. Can you provide a set of files where this doesn't work?

**Comment by AsaAyers** [comment]
Maybe you need to update? That was added in 1.1.0 and 1.3.0 is current.

**Comment by nicolasazrak** [comment]
You are right, I didn't have it updated, thanks for your nice work!

**Comment by AsaAyers** [comment]
fyi `./Foo` is also a link now. It's mostly useful for: 

```
import './Foo`
// or
require('./Foo')
```

For the (hopefully rare) occasion you have to import for a side effect
