### ISSUE TITLE
Expose as keyboard shortcut?

### ISSUE THREAD

**Issue by supercrabtree** [AsaAyers/js-hyperclick#70]
Hi, I would like to be able to press a keyboard shortcut to mimic the clicking action. Is there one currently exposed that I can hook into, or is this something you could add?

**Comment by AsaAyers** [comment]
That is handled by the [`hyperclick`](https://atom.io/packages/hyperclick) package. The default is `<cmd+alt+enter>` or `<ctrl+alt+enter>` depending on your OS.
