### ISSUE TITLE
Support for babel-plugin-module-resolver

### ISSUE THREAD

**Issue by subblue** [AsaAyers/js-hyperclick#71]
For large projects the [babel-plugin-module-resolver](https://github.com/tleunen/babel-plugin-module-resolver) is very useful to avoid long chains of `../../..` in the import paths. It would be brilliant to have that support here :)

[atom-jump-to-import](https://github.com/alexheyd/atom-jump-to-import) supports it, but that plugin isn't as neat as js-hyperclick!

**Comment by penx** [comment]
For anyone wondering why this was closed - it was resolved in https://github.com/AsaAyers/js-hyperclick/pull/32
