### ISSUE TITLE
not recognize .es6 file?

### ISSUE THREAD

**Issue by connectdotz** [AsaAyers/js-hyperclick#73]
Trying to jump to the definition within a `.es6` file didn't work, even though the editor does recognize the javascript syntax in the `.es6` file. js-hyperclick worked if I rename the file to `.js`. 

I did try adding the `.es6` in js-hyperclick's Extensions settings, unfortunately, that didn't make any difference...

thoughts?

**Comment by AsaAyers** [comment]
js-hyperclick doesn't care about the file extension. It only cares about [the scope](https://github.com/AsaAyers/js-hyperclick/blob/master/lib/js-hyperclick.js#L14-L18).

Run this command to find out what scope the file is.
![selection_038](https://cloud.githubusercontent.com/assets/324999/26287775/ceddbe78-3e36-11e7-9c54-531cf7a9c27b.png)

I created a file with the .es6 extension and js-hyperclick works. The command above shows this:
![selection_039](https://cloud.githubusercontent.com/assets/324999/26287785/f8d7d010-3e36-11e7-8df0-1bad09225f40.png)

**Comment by connectdotz** [comment]
scope:
![scope](https://cloud.githubusercontent.com/assets/891093/26287914/99788bca-3e52-11e7-8cf0-4df2d2cf7634.png)

error when clicked:
![screen shot 2017-05-21 at 6 27 18 pm](https://cloud.githubusercontent.com/assets/891093/26287936/4616c22a-3e53-11e7-8eb2-b0841cc0bbf7.png)

-----
ok, found it: the error is from [goto-definition](https://atom.io/packages/goto-definition) plugin. It worked after disabled goto-definition.

All is well, thanks!
