### ISSUE TITLE
Support multiple .js files

### ISSUE THREAD

**Issue by PixelT** [AsaAyers/js-hyperclick#74]
Create files:
- function1.js
- function2.js

in function1.js put:
```
function test(a) {
    console.log(a);
}
```

in function2.js put:
```
test('test log');
```

try to hyperclick on test in function2.js (doesn't work)

**Comment by AsaAyers** [comment]
This project is for [es2015 modules](http://babeljs.io/learn-es2015/#ecmascript-2015-features-modules). It also has backward compatibility with [CommonJS/NodeJS](https://nodejs.org/api/modules.html) style modules.

```js
// function1.js
export function test(a) {
    console.log(a);
}
````

```js
// function2.js
import { test} from './function1.js'

test('test log');
// ^ This will jump to the definition of `test` in function1.js
```
