### ISSUE TITLE
Doesn't  work with import('some/path')

### ISSUE THREAD

**Issue by AStaroverov** [AsaAyers/js-hyperclick#77]

**Comment by tujoworker** [comment]
Not sure why this got closed without more details. But in fact, **import('path')** is in equivalent to import foo from 'path', a dynamic import metode returning a promise.
**import('path')** will get very popular as it is more and more used.

Regarding to this [article](http://2ality.com/2017/01/import-operator.html), webpack is using it for code splitting. And overall is it today wildly supported and used.

## About the Bug
As soon as **import('path')** is somewhere in a file, all the other *hyperclick* support is broken 😿.

**Comment by AsaAyers** [comment]
This was closed because no explanation was provided for the problem. I will look into #85 and provide updates there.
