### ISSUE TITLE
Resolution of folders with index.js files doesn't work

### ISSUE THREAD

**Issue by arfordweb** [AsaAyers/js-hyperclick#79]
I'm writing a React app using Babelify to bundle my code.  I'm able to create files like `src/js/components/Foo/index.jsx` and import them like `import Foo from 'components/Foo';`.  (I added `"moduleRoots": ["./src/js/"],` to my `package.json` file to enable this.)

My issue: `js-hyperclick` doesn't take me to the index.jsx file in that folder.  Instead, it opens a new file called `Foo.js`.  Can `js-hyperclick` be modified to recognize when we're importing an index file in a folder rather than a file named the same as the import path?

**Comment by arfordweb** [comment]
And, of course, as soon as I say that, it stops happening.  Closing unless I can find a more specific example of how to reproduce the issue.

**Comment by AsaAyers** [comment]
`jsx` is not a standard extension. If you want js-hyperclick to look for `.jsx` files it needs to be added here:

![selection_010](https://user-images.githubusercontent.com/324999/28084933-10ecfb42-662f-11e7-8309-1e6b9ca4b167.png)
