### ISSUE TITLE
when I click on a path which is wrong, it opens up an empty editor window

### ISSUE THREAD

**Issue by capaj** [AsaAyers/js-hyperclick#8]
this gets annoying, could you maybe check that the file exists before opening up a new editor window?

The best woul be also some kind of notification that it doesn't exist-something like a red X mark appearing next to the import, but I would be very much content with just preventing empty editor window.

**Comment by AsaAyers** [comment]
This is working as intended. When building something new I'll often `import Thing from './somefile'` and then click through it and go create what I need.

I'll leave the issue open for now though. I'm not sure how to resolve both use cases.

**Comment by capaj** [comment]
You're right, I started to use it like that once I realized it can be used for that. I think the best would be if we could indicate to the user that the file doesn't exist even before ctrl clicking on the path. This will be best solved by a separate package. Hopefully I can get a time to make it some day.
