### ISSUE TITLE
Does not recognise 'atom' module

### ISSUE THREAD

**Issue by Aerijo** [AsaAyers/js-hyperclick#81]
I'm using this package to navigate the code of Atom packages, but it will throw a warning when I click on something imported from `'atom'`. I'm new to JS (and how it works in Atom), and I'm trying to learn how everything in a package fits together. This sometimes leads to me hyperclicking to these Atom classes, only to get a warning that it can't find the Atom module.

It just bugs me that a package written for Atom can't handle this.

Obviously this is not urgent, and I know I can look up the definitions online, but it would be nice if this package could recognise the Atom module and take me to the actual place it's defined, or to the relevant online documentation.

**Comment by AsaAyers** [comment]
I don't like to add special handling for exceptions in this package, but you make a great case that a plugin for Atom can't help you with the `atom` module. Where do you think it should go? Maybe https://atom.io/docs? Would you like figure something out and make a pull request?

The reason it can't locate `atom` is that its module doesn't live in your project's `node_modules`. `js-hyperclick` uses [`resolve`](https://www.npmjs.com/package/resolve), which follows Node's [module resolution algorithm](https://nodejs.org/api/modules.html#modules_all_together). It contains a list of the built in Node modules, so when it returns the same name that was put in, I can just open the docs in the browser.

Contributing quick start:
1. Fork the project on github
2. `git clone [your repo]`
3. `cd js-hyperclick`
4 `apm link` (on a mac you have to find the file menu item to install CLI tools first)
5. "View > Developer > Reload Window" after each change you'd like to test

https://github.com/AsaAyers/js-hyperclick/blob/de6aa1eaa4d06ffc71c8f7bd61641750a33f65ff/lib/core/resolve-module.js#L80-L86

**Comment by AsaAyers** [comment]
Please let me know whether you'd like to try fixing this or if I should when I sit down to work on this project next. Maybe https://atom.io/docs/api/v1.19.0/AtomEnvironment is a better destination.

**Comment by Aerijo** [comment]
Sorry for the late reply.

I would do this myself, but I literally learnt JS a few days ago. I think it would be best if you could come up with a solution, as you know best how the package works. I'll still try to make one though, as a learning exercise.

**Comment by Aerijo** [comment]
Also, it would ideally take you to the exact page it is defined on (eg. https://atom.io/docs/api/v1.19.1/CompositeDisposable for `CompositeDisposable`). However, this might be pushing it. 

If you do any link though, I think https://atom.io/docs/api/latest is the safer way for future compatibility; they seem to have even released an update within the span of this (1.19.1) and your (1.19.0) comment. If an update breaks backwards compatibility, and the intended behaviour in the package doesn't match the documentation, the package itself shouldn't be working. Maybe an extended solution would scan the `package.json` file for max Atom version compatibility?
