### ISSUE TITLE
js-hyperclick not work

### ISSUE THREAD

**Issue by zzgzhang** [AsaAyers/js-hyperclick#83]
I have hyperclick and js-hyperclick both installed in my atom mac10.12 for nodejs.
And i have the package-list below.pls help find any conflict. Thanks. 
Poor English expression, sorry.

Built-in Atom Packages (79)
├── about@1.7.6
├── archive-view@0.63.3
├── autocomplete-atom-api@0.10.1
├── autocomplete-css@0.16.2
├── autocomplete-html@0.8.0
├── autocomplete-plus@2.35.5
├── autocomplete-snippets@1.11.0
├── autoflow@0.29.0
├── autosave@0.24.3
├── background-tips@0.27.1
├── bookmarks@0.44.4
├── bracket-matcher@0.87.3
├── command-palette@0.40.4
├── dalek@0.2.1
├── deprecation-cop@0.56.7
├── dev-live-reload@0.47.1
├── encoding-selector@0.23.4
├── exception-reporting@0.41.4
├── find-and-replace@0.208.3
├── fuzzy-finder@1.5.8
├── github@0.3.4-1
├── git-diff@1.3.6
├── go-to-line@0.32.1
├── grammar-selector@0.49.5
├── image-view@0.61.2
├── incompatible-packages@0.27.3
├── keybinding-resolver@0.38.0
├── line-ending-selector@0.7.3
├── link@0.31.3
├── markdown-preview@0.159.12
├── metrics@1.2.6
├── notifications@0.67.2
├── open-on-github@1.2.1
├── package-generator@1.1.1
├── settings-view@0.250.0
├── snippets@1.1.4
├── spell-check@0.71.4
├── status-bar@1.8.11
├── styleguide@0.49.6
├── symbols-view@0.116.1
├── tabs@0.107.0
├── timecop@0.36.0
├── tree-view@0.217.2
├── update-package-dependencies@0.12.0
├── welcome@0.36.4
├── whitespace@0.37.2
├── wrap-guide@0.40.2
├── language-c@0.58.1
├── language-clojure@0.22.3
├── language-coffee-script@0.48.7
├── language-csharp@0.14.2
├── language-css@0.42.4
├── language-gfm@0.89.1
├── language-git@0.19.1
├── language-go@0.44.1
├── language-html@0.47.3
├── language-hyperlink@0.16.1
├── language-java@0.27.2
├── language-javascript@0.126.1
├── language-json@0.19.1
├── language-less@0.32.0
├── language-make@0.22.3
├── language-mustache@0.14.1
├── language-objective-c@0.15.1
├── language-perl@0.37.0
├── language-php@0.39.0
├── language-property-list@0.9.1
├── language-python@0.45.3
├── language-ruby@0.71.1
├── language-ruby-on-rails@0.25.2
├── language-sass@0.59.0
├── language-shellscript@0.25.1
├── language-source@0.9.0
├── language-sql@0.25.6
├── language-text@0.7.3
├── language-todo@0.29.1
├── language-toml@0.18.1
├── language-xml@0.35.1
└── language-yaml@0.30.0

Community Packages (15) /~~~/.atom/packages
├── atom-beautify@0.30.5
├── atom-pigments@0.40.2
├── atom-script@3.15.0
├── atom-ternjs@0.18.3
├── browser-plus@0.0.98
├── busy-signal@1.4.3
├── docblockr@0.11.0
├── highlight-selected@0.13.1
├── hyperclick@0.1.3
├── intentions@1.1.5
├── js-hyperclick@1.11.0
├── linter@2.2.0
├── linter-jshint@3.1.5
├── linter-ui-default@1.6.8
└── minimap@4.29.6

**Comment by zzgzhang** [comment]
replace hyperclick@0.1.3 with atom-ide-ui , solved. Sorry again.

**Comment by AsaAyers** [comment]
There's no need to apologize, this is exactly what this issue tracker is for. I'm also using hyperclick@0.1.3, so I don't know why changing packages fixed it for you. Since I can't reproduce the issue and you've solved  it on your end I'll leave this issue closed.

**Comment by zzgzhang** [comment]
Oh, it was really not fixed by changing package to atom-ide-ui.
I think the issue did not happen in js-hyperclick but in hyperclick.
cause, when i changed hyperclick@0.1.3 with atom-ide-ui, the hyperclick builded in atom-ide-ui works fine, and i can jump code defination only in single file.(not work such as test = require('./test'), and i want to open test function in test.js ).
Then i tried uninstall hyperclick , js-hyperclick alerted need dependence hyperclick...

very confused but closed.
