### ISSUE TITLE
Dynamic import('path') breaks hyperclick 😿

### ISSUE THREAD

**Issue by tujoworker** [AsaAyers/js-hyperclick#85]
## About the Bug
As soon as **import('path')** is somewhere in a file, all the other *hyperclick* support is broken 😿.

### About Dynamic Import
**import('path')** is in equivalent to *import foo from 'path'*, a dynamic import metode returning a promise. **import('path')** will get very popular as it is more and more used.

Regarding to this [article](http://2ality.com/2017/01/import-operator.html), webpack is using it for code splitting. And overall is it today wildly supported and used.

**Comment by AsaAyers** [comment]
In the version of Babel that js-hyperclick uses, `import('path')` is a syntax error. Any syntax error prevents js-hyperclick from working.

**Comment by tujoworker** [comment]
Thanks a lot for the quick answer! Could You add this plugin? 
https://www.npmjs.com/package/babel-plugin-syntax-dynamic-import

--
This email was sent on the road.

**Comment by AsaAyers** [comment]
Thanks, I can't just add that plugin directly, looking at the code did point me in the right direction. I have a branch that stops the syntax error, next I need to make sure `import()` is followed similar to a `require()`.

**Comment by tujoworker** [comment]
Thanks, sounds good! 😊

**Comment by tujoworker** [comment]
Huge thank You @AsaAyers ♥️ - it works like a charm!
