### ISSUE TITLE
hyperclick dependency not needed with atom-ide-ui

### ISSUE THREAD

**Issue by UziTech** [AsaAyers/js-hyperclick#86]
![image](https://user-images.githubusercontent.com/97994/32678590-9704155e-c628-11e7-9b51-9847266ee0c0.png)

[`atom-ide-ui`](https://github.com/facebook-atom/atom-ide-ui) also includes hyperclick

**Comment by AsaAyers** [comment]
Thanks for the reminder to fix this. I just published 1.12.2 that doesn't prompt if you have `atom-ide-ui` installed.
