### ISSUE TITLE
Losing focus after a jump

### ISSUE THREAD

**Issue by Lacroute** [AsaAyers/js-hyperclick#87]
Hi,

I'm not sure if it's relative to js-hyperclick or just hyperclick but after a jump, I can't use the letters of my keyboard. Only the shortcuts and tab, enter, backspace key are working.

It appears in a "file jump" only if the file was already opened in a tab or in a "constant jump".
I have to click on the jumped file to have the focus back and code again.

I'm using Atom, in macOS 10.13.2

**Comment by AsaAyers** [comment]
I'm not able to reproduce this problem. I suspect one of your other plugins is interfering when you land at the destination. Try disabling everything but `js-hyperclick` and `hyperclick`.

Is "constant jump" when it jumps to a local variable in the same file? There are 4 categories of jumps that have never had names before:

1. Jump to a local variable in this file
2. Jump to an imported variable. clicking `foo` in a file with an `import foo from './foo.js'` opens `foo.js` and moves the cursor to the export
3. Jump to a file. You can click the `'./foo.js'` in the import to jump to the file.
4. If the destination module is built into node (ex: `path`) it opens the browser and jumps to the documentation.
    * For me `ide-flowtype` triggers first, so I get its behavior instead of docs in the browser.

**Comment by Lacroute** [comment]
Thanks for your answer. I found a more precise way to reproduce it, it is related to hyperclick and the trigger keys for macOS. If I map the control + click there it happens, otherwise it works normally.
I'm creating the issue on hyperclick package.

Thanks for your package that helps me a lot 👍
