### ISSUE TITLE
what about symlinks?

### ISSUE THREAD

**Issue by patriciussanctus** [AsaAyers/js-hyperclick#91]
my submodule use symlinks, how i can get access to files via hyperclick?

<img width="1002" alt="2018-03-14 17 03 43" src="https://user-images.githubusercontent.com/16253399/37407052-cede4318-27a9-11e8-8fa3-f86a6442079e.png">

<!--
Please go read the FAQ in this project's README.md before opening your issue.
--!>

**Comment by AsaAyers** [comment]
None of your paths there are relative to the current file, so `js-hyperclick` is going to follow [Node's resolution algorithm](https://nodejs.org/api/modules.html#modules_all_together). If `custom-ui` is in a `node_modules` next to `entity.js`, or any directory above it this should work fine. I don't think js-hyperclick has a problem with symlinks, I think you're probably looking for [moduleRoots](https://github.com/AsaAyers/js-hyperclick#i-configured-babeleslintflowwebpacketc-to-avoid--in-my-imports-how-can-i-configure-js-hyperclick).

**Comment by patriciussanctus** [comment]
@AsaAyers oh sure, I'm sorry, I got confused in the repositories %D
