### ISSUE TITLE
useing in *.vue,if had a '@' js-hyperclick  not work!!

### ISSUE THREAD

**Issue by petsgre** [AsaAyers/js-hyperclick#92]
<!--
Please go read the FAQ in this project's README.md before opening your issue.
--!>
like this , import api from '@/api/Api.js'

if you had '@' ,the js-hyperclick is not useful,could you reslove it ?

**Comment by petsgre** [comment]
it tell me that 'module @/api/Api.js was not found'

**Comment by AsaAyers** [comment]
Closing as a duplicate of https://github.com/AsaAyers/js-hyperclick/issues/58

**Comment by AsaAyers** [comment]
I just published v1.15 with a new feature I'm calling "Custom Resolvers". It will allow you to add a JS file to your project that can implement your aliases. [PR and documentation](https://github.com/AsaAyers/js-hyperclick/pull/105)
