### ISSUE TITLE
What syntax theme are you using in your screenshot?

### ISSUE THREAD

**Issue by schoenflies** [AsaAyers/js-hyperclick#98]
<!--
Please go read the FAQ in this project's README.md before opening your issue.
--!>

This doesn't have anything to do with the library directly, I'm just wondering what syntax theme you're using in the screenshot 
![1_2bblq4gcj4ovhox05ba32q](https://user-images.githubusercontent.com/7926601/45591810-b28ab580-b92a-11e8-9dd1-d82a6394b871.png)
and what font it is if you remember since I can't get my font and syntax highlighting to match.
Thanks

**Comment by AsaAyers** [comment]
I think that's the [Ubuntu Mono](https://design.ubuntu.com/font/) font and I don't know what theme I was using. it seems like https://atom.io/packages/fonts can install/configure the Ubuntu Mono font.
